Cfdi Test updates
NTlink/ntlink-ws-sdk pull request #16
Opened 2022-04-05 20:48 UTC by Vic281291

correction & validations XML files

2022-04-05 20:50 UTC, avelinonscorp submitted a review, later dismissed

2022-04-06 01:56 UTC, ralfdemoledor commented on src/test/java/com/mx/ntlink/client/NtLinkClientNominaTest.java
> +    String comprobante =
Este archivo no se encuentra en los recursos

2022-04-06 01:57 UTC, ralfdemoledor requested changes
El archivo `/src/test/resources/nomina-error/NOM32.xml` no existe

2022-04-08 21:56 UTC, ralfdemoledor submitted a review, later dismissed

2022-04-12 17:58 UTC, closed without merging